import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, onAuthStateChanged, GoogleAuthProvider, signInWithPopup, signOut, setPersistence, browserLocalPersistence } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, collection, getDocs, doc, setDoc, deleteDoc } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import { getStorage, ref as storageRef, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-storage.js";

const FIREBASE_CONFIG={
  apiKey:"AIzaSyAZwvHGXmi_m_a8KqZbxELHAlV0ah1SWO8",
  authDomain:"idea-pocket-56063.firebaseapp.com",
  projectId:"idea-pocket-56063",
  storageBucket:"idea-pocket-56063.firebasestorage.app",
  messagingSenderId:"894399979515",
  appId:"1:894399979515:web:834a298e37ef05dbd0f55e"
};
const BOOK_SEARCH_PROXY="https://us-central1-idea-pocket-56063.cloudfunctions.net/bookSearch";
const ACTIVE_SESSION_KEY="readingGarden_activeSession_v1";
const CURRENT_BOOK_KEY="readingGarden_currentBook_v1";
const SNAPSHOT_DB="readingGarden_v1";
const DB_VERSION=1;
const COLLECTIONS=["readingProfiles","readingCycles","readingSessions","readingEntries","readingPaths"];
const $=id=>document.getElementById(id);
const $$=sel=>[...document.querySelectorAll(sel)];
const nowIso=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const esc=(v="")=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const localDate=v=>{const d=v?new Date(v):new Date();return Number.isNaN(d.getTime())?"":d.toLocaleDateString("en-CA")};
const displayDate=v=>{const d=v?new Date(v):new Date();return new Intl.DateTimeFormat("ko-KR",{month:"long",day:"numeric",weekday:"short"}).format(d)};
const displayDateFull=v=>{const d=v?new Date(v):new Date();return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"long",day:"numeric"}).format(d)};
const timeText=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?"":new Intl.DateTimeFormat("ko-KR",{hour:"2-digit",minute:"2-digit",hour12:false}).format(d)};
const fmtMinutes=n=>{n=Math.max(0,Math.round(Number(n)||0));if(n<60)return `${n}분`;const h=Math.floor(n/60),m=n%60;return m?`${h}시간 ${m}분`:`${h}시간`};
const safeText=v=>String(v??"").trim();

const STATUS_LABELS={wishlist:"읽고 싶음",reading:"읽는 중",paused:"잠시 멈춤",completed:"완독",dnf:"중단"};
const FORMAT_LABELS={ebook:"전자책",paper:"종이책",pdf:"PDF",audiobook:"오디오북",other:"기타"};
const SERVICE_LABELS={millie:"밀리의 서재",yes24:"YES24",paper:"종이책",other:"기타"};

const state={
  user:null,db:null,storage:null,cloudReady:false,loading:true,
  sources:[],fragments:[],readingProfiles:[],readingCycles:[],readingSessions:[],readingEntries:[],readingPaths:[],
  currentView:"read",libraryMode:"books",libraryStatus:"reading",timelineFilter:"all",statsRange:"month",
  currentBookId:null,detailBookId:null,detailTab:"timeline",activeSession:null,timerHandle:null,selectedFeel:"",
  editingEntryId:null,recordReturnToSession:true,
  handwriting:{strokes:[],current:null,width:2.5,eraser:false,draft:null,dpr:1},
  idb:null,syncing:false,bookApiResults:[]
};

function toast(msg,ms=2400){const e=$("toast");e.textContent=msg;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),ms)}
function openDialog(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDialog(id){const d=$(id);if(d?.open)d.close()}
function openLayer(id){const e=$(id);e.classList.remove("hidden");e.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeLayer(id){const e=$(id);e.classList.add("hidden");e.setAttribute("aria-hidden","true");document.body.style.overflow=""}

async function openIdb(){
  return new Promise((resolve,reject)=>{
    const req=indexedDB.open(SNAPSHOT_DB,DB_VERSION);
    req.onupgradeneeded=()=>{
      const db=req.result;
      if(!db.objectStoreNames.contains("outbox"))db.createObjectStore("outbox",{keyPath:"id"});
      if(!db.objectStoreNames.contains("files"))db.createObjectStore("files",{keyPath:"id"});
      if(!db.objectStoreNames.contains("meta"))db.createObjectStore("meta",{keyPath:"key"});
    };
    req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);
  });
}
function idbTx(store,mode="readonly"){return state.idb.transaction(store,mode).objectStore(store)}
function idbPut(store,val){return new Promise((resolve,reject)=>{const r=idbTx(store,"readwrite").put(val);r.onsuccess=()=>resolve(val);r.onerror=()=>reject(r.error)})}
function idbDelete(store,key){return new Promise((resolve,reject)=>{const r=idbTx(store,"readwrite").delete(key);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function idbGetAll(store){return new Promise((resolve,reject)=>{const r=idbTx(store).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function idbGet(store,key){return new Promise((resolve,reject)=>{const r=idbTx(store).get(key);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}

async function cacheSnapshot(){
  if(!state.idb)return;
  const snapshot={key:"snapshot",savedAt:nowIso(),sources:state.sources.filter(s=>s.type==="book"),readingProfiles:state.readingProfiles,readingCycles:state.readingCycles,readingSessions:state.readingSessions,readingEntries:state.readingEntries.map(e=>({...e,handwritingLocalUrl:undefined})),readingPaths:state.readingPaths};
  try{await idbPut("meta",snapshot)}catch{}
}
async function loadSnapshot(){
  if(!state.idb)return false;
  const x=await idbGet("meta","snapshot");if(!x)return false;
  for(const k of ["sources","readingProfiles","readingCycles","readingSessions","readingEntries","readingPaths"])state[k]=Array.isArray(x[k])?x[k]:[];
  return true;
}

async function queueOp(collectionName,docId,data,kind="set"){
  await idbPut("outbox",{id:`${collectionName}:${docId}`,collectionName,docId,data,kind,queuedAt:nowIso()});updateSyncInfo();
}
async function cloudSet(collectionName,docId,data,{silent=false}={}){
  const clean=JSON.parse(JSON.stringify(data));
  if(!state.cloudReady||!navigator.onLine){await queueOp(collectionName,docId,clean,"set");if(!silent)toast("기기에 저장했습니다. 연결되면 동기화합니다.");return false}
  try{await setDoc(doc(state.db,"users",state.user.uid,collectionName,docId),clean,{merge:true});return true}
  catch(err){console.warn("cloudSet queued",collectionName,err);await queueOp(collectionName,docId,clean,"set");if(!silent)toast("기기에 안전하게 저장했습니다. 동기화를 다시 시도합니다.");return false}
}
async function cloudDelete(collectionName,docId){
  if(!state.cloudReady||!navigator.onLine){await queueOp(collectionName,docId,null,"delete");return false}
  try{await deleteDoc(doc(state.db,"users",state.user.uid,collectionName,docId));return true}catch(err){await queueOp(collectionName,docId,null,"delete");return false}
}
async function queueFile(file){await idbPut("files",file);updateSyncInfo()}
async function uploadAsset(file){const r=storageRef(state.storage,file.path);await uploadBytes(r,file.blob,{contentType:file.contentType});return getDownloadURL(r)}
async function saveHandwritingFiles(entry){
  const d=state.handwriting.draft;if(!d?.imageBlob)return;
  const base=`users/${state.user.uid}/reading/${entry.sourceId}/${entry.id}`;
  const imageFile={id:`${entry.id}:image`,entryId:entry.id,kind:"image",path:`${base}/handwriting.webp`,blob:d.imageBlob,contentType:"image/webp"};
  entry.handwritingPending=true;entry.strokeFileUrl=null;entry.updatedAt=nowIso();
  await queueFile(imageFile);
  await queueOp("readingEntries",entry.id,JSON.parse(JSON.stringify(entry)),"set");
  void flushSync();
}
async function flushSync(){
  if(state.syncing||!state.cloudReady||!navigator.onLine||!state.idb)return;
  state.syncing=true;let doneDocs=0,doneFiles=0;
  try{
    const ops=await idbGetAll("outbox");
    for(const op of ops){try{const ref=doc(state.db,"users",state.user.uid,op.collectionName,op.docId);if(op.kind==="delete")await deleteDoc(ref);else await setDoc(ref,op.data,{merge:true});await idbDelete("outbox",op.id);doneDocs++}catch(err){console.warn("sync op failed",op,err);break}}
    const files=await idbGetAll("files"),byEntry={};
    for(const f of files){try{const url=await uploadAsset(f);(byEntry[f.entryId]??={})[f.kind==="image"?"handwritingImageUrl":"strokeFileUrl"]=url;await idbDelete("files",f.id);doneFiles++}catch(err){console.warn("sync file failed",f,err);break}}
    for(const [entryId,patch] of Object.entries(byEntry)){const e=state.readingEntries.find(x=>x.id===entryId);if(e)Object.assign(e,patch,{handwritingPending:false,updatedAt:nowIso()});await setDoc(doc(state.db,"users",state.user.uid,"readingEntries",entryId),{...patch,handwritingPending:false,updatedAt:nowIso()},{merge:true})}
    if(doneDocs||doneFiles)toast(`☁️ ${doneDocs?`기록 ${doneDocs}건`:""}${doneDocs&&doneFiles?" · ":""}${doneFiles?`필사 이미지 ${doneFiles}개`:""} 동기화되었습니다.`);
  }finally{state.syncing=false;updateSyncInfo();cacheSnapshot()}
}
async function updateSyncInfo(){if(!state.idb)return;const [ops,files]=await Promise.all([idbGetAll("outbox"),idbGetAll("files")]);const n=ops.length+files.length;if($("syncInfo"))$("syncInfo").textContent=n?`☁️ 동기화 대기 ${n}건 · 기기에 안전하게 보관 중`:state.cloudReady&&navigator.onLine?"☁️ 동기화 완료":"☁️ 오프라인 저장 중"}

async function initFirebase(){
  const app=initializeApp(FIREBASE_CONFIG),auth=getAuth(app);state.db=getFirestore(app);state.storage=getStorage(app);
  try{await setPersistence(auth,browserLocalPersistence)}catch{}
  $("googleLoginBtn").addEventListener("click",async()=>{try{await signInWithPopup(auth,new GoogleAuthProvider())}catch(err){$("authGateStatus").textContent=`로그인 실패: ${err.message}`}});
  $("signOutBtn").addEventListener("click",async()=>signOut(auth));
  onAuthStateChanged(auth,async user=>{state.user=user;if(!user){state.cloudReady=false;$("authGate").classList.remove("hidden");$("authGateStatus").textContent="생각의 텃밭에서 쓰는 Google 계정으로 연결해주세요.";return}$("authGate").classList.add("hidden");state.cloudReady=true;$("accountInfo").textContent=user.displayName||user.email||"Google 계정 연결됨";await loadCloudData();await flushSync();renderAll()});
}
async function loadCollection(name){try{const snap=await getDocs(collection(state.db,"users",state.user.uid,name));return snap.docs.map(d=>({id:d.id,...d.data()}))}catch(err){console.warn("load collection failed",name,err);return null}}
async function loadCloudData(){
  state.loading=true;const sources=await loadCollection("sources");if(sources)state.sources=sources.filter(s=>s.type==="book");else await loadSnapshot();const fragments=await loadCollection("fragments");state.fragments=fragments||[];for(const name of COLLECTIONS){const data=await loadCollection(name);if(data)state[name]=data}
  const activeRaw=localStorage.getItem(ACTIVE_SESSION_KEY);if(activeRaw){try{state.activeSession=JSON.parse(activeRaw)}catch{localStorage.removeItem(ACTIVE_SESSION_KEY)}}state.currentBookId=localStorage.getItem(CURRENT_BOOK_KEY)||chooseCurrentBookId();state.loading=false;await cacheSnapshot();updateSyncInfo();
}

function inferService(platform=""){const p=String(platform).toLowerCase();if(p.includes("밀리"))return "millie";if(p.includes("yes24")||p.includes("예스24"))return "yes24";if(p.includes("종이"))return "paper";return "other"}
function inferFormat(platform=""){const s=inferService(platform);if(s==="millie"||s==="yes24")return "ebook";if(s==="paper")return "paper";if(String(platform).includes("오디오"))return "audiobook";return "ebook"}
function sourceById(id){return state.sources.find(x=>x.id===id)}
function profileById(sourceId){return state.readingProfiles.find(x=>x.sourceId===sourceId)}
function getProfile(sourceId){const real=profileById(sourceId);if(real)return real;const s=sourceById(sourceId);if(!s)return null;return {id:`virtual:${sourceId}`,sourceId,status:s.status==="done"?"completed":"reading",format:inferFormat(s.platform),service:inferService(s.platform),currentLocator:"",startedAt:s.createdAt||"",lastReadAt:"",completedAt:s.status==="done"?(s.updatedAt||""):null,_virtual:true}}
function ensureProfile(sourceId){let p=profileById(sourceId);if(p)return p;const v=getProfile(sourceId);p={...v,id:uid(),_virtual:undefined,createdAt:nowIso(),updatedAt:nowIso()};state.readingProfiles.push(p);cloudSet("readingProfiles",p.id,p,{silent:true});return p}
function readingBooks(){return state.sources.filter(s=>getProfile(s.id)?.status==="reading")}
function chooseCurrentBookId(){const books=readingBooks();books.sort((a,b)=>new Date(getProfile(b.id)?.lastReadAt||b.updatedAt||0)-new Date(getProfile(a.id)?.lastReadAt||a.updatedAt||0));return books[0]?.id||state.sources[0]?.id||null}
function setCurrentBook(id){state.currentBookId=id;localStorage.setItem(CURRENT_BOOK_KEY,id);renderRead()}
function serviceText(p){return SERVICE_LABELS[p?.service]||FORMAT_LABELS[p?.format]||"독서"}
function coverHtml(s,cls="hero-cover"){return s?.image?`<img class="${cls}" src="${esc(s.image)}" alt="${esc(s.title)} 표지" />`:`<div class="${cls} placeholder">📕</div>`}
function setView(view){state.currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.nav-btn').forEach(b=>b.classList.toggle('on',b.dataset.viewTarget===view));if(view==="read")renderRead();if(view==="library")renderLibrary();if(view==="timeline")renderTimeline();if(view==="stats")renderStats()}
function renderAll(){renderRead();renderLibrary();renderTimeline();renderStats();renderTimelineBookOptions();renderPaths()}

function renderRead(){
  const box=$("readHero");if(state.loading){box.innerHTML=`<div class="empty-hero"><p>서재를 불러오고 있어요…</p></div>`;return}
  if(state.activeSession&&!state.activeSession.endedAt){const s=sourceById(state.activeSession.sourceId);box.innerHTML=`<div class="read-hero-inner"><div class="notice" style="margin-bottom:18px">진행 중이던 독서가 있어요.</div>${coverHtml(s)}<h2 class="hero-title">${esc(s?.title||"읽던 책")}</h2><p class="hero-author">${esc(s?.creator||"")}</p><button class="btn primary block start-btn" data-resume-session type="button">▶ 독서 계속하기</button><button class="text-btn switch-book" data-abandon-session type="button">종료 처리하기</button></div>`;return}
  const s=sourceById(state.currentBookId)||sourceById(chooseCurrentBookId());if(!s){box.innerHTML=`<div class="empty-hero"><div class="empty-icon">📚</div><h2>읽을 책을 골라볼까요?</h2><p>생각의 텃밭에 등록한 책이 있으면 같은 서재에서 자동으로 불러옵니다.</p><button class="btn primary" data-open-book-search type="button">＋ 책 추가</button></div>`;return}
  state.currentBookId=s.id;const p=getProfile(s.id),isPhysical=p?.format==="paper"||p?.format==="pdf",locator=safeText(p?.currentLocator);
  box.innerHTML=`<div class="read-hero-inner">${coverHtml(s)}<h2 class="hero-title">${esc(s.title)}</h2><p class="hero-author">${esc(s.creator||"")}</p><span class="hero-service">${esc(serviceText(p))}</span>${isPhysical&&locator?`<div class="hero-locator"><small>지난번 위치</small><strong>${esc(nextLocator(locator,p.format))}</strong></div>`:p?.lastReadAt?`<div class="hero-locator"><small>최근 독서</small><strong style="font-size:1rem">${esc(relativeDate(p.lastReadAt))}</strong></div>`:""}<button class="btn primary block start-btn" data-start-book="${esc(s.id)}" type="button">▶ 읽기 시작</button><button class="text-btn switch-book" data-open-book-picker type="button">다른 책 선택 ›</button></div>`;
}
function nextLocator(locator,format){if(format!=="paper"&&format!=="pdf")return locator;const m=String(locator).match(/(?:p\.\s*)?(\d+)/i);return m?`p.${Number(m[1])+1}부터`:locator}
function relativeDate(v){const d=new Date(v),today=new Date();today.setHours(0,0,0,0);const x=new Date(d);x.setHours(0,0,0,0);const days=Math.round((today-x)/86400000);return days===0?"오늘":days===1?"어제":`${days}일 전`}

function renderLibrary(){const statuses=["reading","wishlist","paused","completed","dnf"];$("libraryStatusChips").innerHTML=statuses.map(x=>`<button class="chip-btn ${state.libraryStatus===x?"on":""}" data-library-status="${x}" type="button">${STATUS_LABELS[x]}</button>`).join("");$("libraryBooksPanel").classList.toggle("hidden",state.libraryMode!=="books");$("pathsPanel").classList.toggle("hidden",state.libraryMode!=="paths");if(state.libraryMode!=="books")return;const q=safeText($("librarySearch")?.value).toLowerCase(),books=state.sources.filter(s=>getProfile(s.id)?.status===state.libraryStatus).filter(s=>!q||`${s.title} ${s.creator}`.toLowerCase().includes(q));$("libraryGrid").innerHTML=books.length?books.map(s=>{const p=getProfile(s.id);return `<article class="book-card" data-open-book="${esc(s.id)}">${coverHtml(s,"book-card-cover")}<h3>${esc(s.title)}</h3><p>${esc(s.creator||"")}</p><div class="book-card-meta"><span class="mini-tag">${esc(serviceText(p))}</span>${p?.currentLocator?`<span class="mini-tag">${esc(p.currentLocator)}</span>`:""}</div></article>`}).join(""):`<div class="empty-card">${STATUS_LABELS[state.libraryStatus]} 책이 없습니다.</div>`}
function renderPaths(){const box=$("pathsList");if(!box)return;box.innerHTML=state.readingPaths.length?state.readingPaths.map(p=>{const ids=p.sourceIds||[],done=ids.filter(id=>getProfile(id)?.status==="completed").length,pct=ids.length?Math.round(done/ids.length*100):0;return `<article class="path-card"><h3>${esc(p.title)}</h3>${p.description?`<p>${esc(p.description)}</p>`:""}<p>${done} / ${ids.length}</p><div class="path-progress"><span style="width:${pct}%"></span></div></article>`}).join(""):`<div class="empty-card">아직 Reading Path가 없습니다.</div>`}
function bookMetrics(sourceId){const ss=state.readingSessions.filter(s=>s.sourceId===sourceId&&s.endedAt),entries=state.readingEntries.filter(e=>e.sourceId===sourceId),mins=ss.reduce((a,b)=>a+(Number(b.finalDurationMinutes)||0),0),days=new Set(ss.map(s=>localDate(s.startedAt))).size;return {mins,days,sessions:ss.length,entries,quotes:entries.filter(e=>safeText(e.quoteText||e.confirmedText)).length,handwriting:entries.filter(e=>e.inputMethod==="handwriting").length,thoughts:entries.filter(e=>safeText(e.thought)).length}}
function openBookDetail(id){state.detailBookId=id;state.detailTab="timeline";renderBookDetail();openLayer("bookDetail")}
function renderBookDetail(){const s=sourceById(state.detailBookId);if(!s)return;const p=getProfile(s.id),m=bookMetrics(s.id),detailTimeline=renderTimelineHtml({bookId:s.id,embedded:true});$("bookDetailBody").innerHTML=`<div class="detail-hero">${coverHtml(s,"detail-cover")}<div class="detail-meta"><h2>${esc(s.title)}</h2><p>${esc(s.creator||"")}</p><div class="detail-tags"><span class="mini-tag">${esc(STATUS_LABELS[p.status])}</span><span class="mini-tag">${esc(serviceText(p))}</span>${p.currentLocator?`<span class="mini-tag">${esc(p.currentLocator)}</span>`:""}</div></div></div><button class="btn primary block detail-start" data-start-book="${esc(s.id)}" type="button">▶ 읽기 시작</button><div class="detail-metrics"><div class="detail-metric"><small>총 독서시간</small><strong>${fmtMinutes(m.mins)}</strong></div><div class="detail-metric"><small>읽은 날</small><strong>${m.days}일</strong></div></div><div id="bookMoreMenu" class="more-menu hidden"><button class="btn" data-edit-profile="${esc(s.id)}" type="button">읽기 설정 수정</button><button class="btn" data-complete-book="${esc(s.id)}" type="button">◉ 완독 처리</button><button class="btn" data-print-book="${esc(s.id)}" type="button">📄 이 책 기록 PDF / 인쇄</button></div><div class="segmented detail-tabs"><button class="seg ${state.detailTab==="timeline"?"on":""}" data-detail-tab="timeline" type="button">기록</button><button class="seg ${state.detailTab==="stats"?"on":""}" data-detail-tab="stats" type="button">통계</button></div><div id="detailTabBody">${state.detailTab==="timeline"?detailTimeline:renderBookStatsHtml(s.id)}</div>`}
function renderBookStatsHtml(id){const m=bookMetrics(id);return `<div class="stats-summary"><div class="stat-card"><small>총 시간</small><strong>${fmtMinutes(m.mins)}</strong></div><div class="stat-card"><small>세션</small><strong>${m.sessions}회</strong></div><div class="stat-card"><small>필사</small><strong>${m.handwriting}</strong></div><div class="stat-card"><small>생각</small><strong>${m.thoughts}</strong></div></div>`}

function ensureCycle(sourceId){let c=state.readingCycles.find(x=>x.sourceId===sourceId&&!x.completedAt);if(c)return c;const prior=state.readingCycles.filter(x=>x.sourceId===sourceId);c={id:uid(),sourceId,sequence:prior.length+1,format:getProfile(sourceId)?.format||"ebook",service:getProfile(sourceId)?.service||"other",startedAt:nowIso(),completedAt:null,finalReflection:"",oneLineReflection:"",rereadWanted:false,createdAt:nowIso(),updatedAt:nowIso()};state.readingCycles.push(c);cloudSet("readingCycles",c.id,c,{silent:true});return c}
async function startSession(sourceId){if(state.activeSession&&!state.activeSession.endedAt){toast("이미 진행 중인 독서가 있어요.");return}const s=sourceById(sourceId);if(!s)return;const p=ensureProfile(sourceId);if(p.status!=="reading"){p.status="reading";p.updatedAt=nowIso();await cloudSet("readingProfiles",p.id,p,{silent:true})}const c=ensureCycle(sourceId),session={id:uid(),sourceId,cycleId:c.id,startedAt:nowIso(),endedAt:null,rawDurationMinutes:0,measuredDurationMinutes:0,finalDurationMinutes:0,durationAdjusted:false,startLocator:p.currentLocator||"",endLocator:"",format:p.format,service:p.service,readingFeel:"",sessionNote:"",pausedMs:0,pauseStartedAt:null,pauses:[],createdAt:nowIso(),updatedAt:nowIso()};state.activeSession=session;localStorage.setItem(ACTIVE_SESSION_KEY,JSON.stringify(session));await cloudSet("readingSessions",session.id,session,{silent:true});openSession(session)}
function openSession(session=state.activeSession){if(!session)return;state.activeSession=session;const s=sourceById(session.sourceId);$("sessionBookTitle").textContent=s?.title||"독서";$("sessionService").textContent=serviceText(getProfile(session.sourceId));openLayer("sessionLayer");startTimer()}
function sessionElapsedMs(session=state.activeSession){if(!session)return 0;const start=new Date(session.startedAt).getTime(),end=session.endedAt?new Date(session.endedAt).getTime():Date.now();let paused=Number(session.pausedMs)||0;if(session.pauseStartedAt&&!session.endedAt)paused+=Date.now()-new Date(session.pauseStartedAt).getTime();return Math.max(0,end-start-paused)}
function formatClock(ms){const sec=Math.floor(ms/1000),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
function startTimer(){clearInterval(state.timerHandle);const tick=()=>{if(!state.activeSession)return;const t=formatClock(sessionElapsedMs());$("sessionClock").textContent=t;$("sessionClockTop").textContent=t;const paused=!!state.activeSession.pauseStartedAt;$("sessionLayer").classList.toggle("session-paused",paused);$("sessionStateText").textContent=paused?"잠시 멈춤":"읽는 중";$("pauseSessionBtn").textContent=paused?"다시 읽기":"일시정지"};tick();state.timerHandle=setInterval(tick,1000)}
async function togglePause(){const s=state.activeSession;if(!s)return;if(s.pauseStartedAt){const ended=Date.now(),started=new Date(s.pauseStartedAt).getTime();s.pausedMs=(Number(s.pausedMs)||0)+(ended-started);s.pauses.push({startedAt:s.pauseStartedAt,endedAt:new Date(ended).toISOString()});s.pauseStartedAt=null}else s.pauseStartedAt=nowIso();s.updatedAt=nowIso();localStorage.setItem(ACTIVE_SESSION_KEY,JSON.stringify(s));await cloudSet("readingSessions",s.id,s,{silent:true});startTimer()}
function openEndSession(){const s=state.activeSession;if(!s)return;const wall=Math.max(1,Math.round((Date.now()-new Date(s.startedAt).getTime())/60000)),measured=Math.max(1,Math.round(sessionElapsedMs(s)/60000));$("sessionMeasured").innerHTML=`시작 <b>${timeText(s.startedAt)}</b><br>현재 <b>${timeText(nowIso())}</b><br><span class="helper">측정 시간 ${fmtMinutes(measured)} · 경과 ${fmtMinutes(wall)}</span>`;$("finalDuration").value=measured;$("endLocator").value=getProfile(s.sourceId)?.currentLocator||"";$("sessionNote").value="";state.selectedFeel="";$$('.feel-btn').forEach(b=>b.classList.remove('on'));openDialog("endSessionDialog")}
async function finishSession(){
  const s=state.activeSession;if(!s)return;const ended=nowIso();if(s.pauseStartedAt){const started=new Date(s.pauseStartedAt).getTime();s.pausedMs=(Number(s.pausedMs)||0)+(Date.now()-started);s.pauses.push({startedAt:s.pauseStartedAt,endedAt:ended});s.pauseStartedAt=null}
  const raw=Math.max(1,Math.round((new Date(ended)-new Date(s.startedAt))/60000)),measured=Math.max(1,Math.round((new Date(ended)-new Date(s.startedAt)-(Number(s.pausedMs)||0))/60000)),finalM=Math.max(1,Number($("finalDuration").value)||measured);Object.assign(s,{endedAt:ended,rawDurationMinutes:raw,measuredDurationMinutes:measured,finalDurationMinutes:finalM,durationAdjusted:finalM!==measured,endLocator:safeText($("endLocator").value),readingFeel:state.selectedFeel,sessionNote:safeText($("sessionNote").value),updatedAt:nowIso()});const es=state.readingEntries.filter(e=>e.sessionId===s.id);Object.assign(s,{entryCount:es.length,quoteCount:es.filter(e=>safeText(e.quoteText||e.confirmedText)).length,handwritingCount:es.filter(e=>e.inputMethod==="handwriting").length,thoughtCount:es.filter(e=>safeText(e.thought)).length});const existing=state.readingSessions.findIndex(x=>x.id===s.id);if(existing>=0)state.readingSessions[existing]={...s};else state.readingSessions.push({...s});await cloudSet("readingSessions",s.id,s);const p=ensureProfile(s.sourceId);p.lastReadAt=ended;if(s.endLocator)p.currentLocator=s.endLocator;p.updatedAt=nowIso();await cloudSet("readingProfiles",p.id,p,{silent:true});state.currentBookId=s.sourceId;localStorage.setItem(CURRENT_BOOK_KEY,s.sourceId);state.activeSession=null;localStorage.removeItem(ACTIVE_SESSION_KEY);clearInterval(state.timerHandle);closeDialog("endSessionDialog");closeLayer("sessionLayer");await cacheSnapshot();renderAll();toast(`오늘 ${fmtMinutes(finalM)} 읽었습니다. 🌿`)
}

function openRecord({entry=null,fromSession=true}={}){state.recordReturnToSession=fromSession;state.editingEntryId=entry?.id||null;$("entryLocator").value=entry?.locator||(state.activeSession?getProfile(state.activeSession.sourceId)?.currentLocator||"":"");$("entryQuote").value=entry?.quoteText||entry?.confirmedText||"";$("entryThought").value=entry?.thought||"";$("deleteEntryBtn").classList.toggle("hidden",!entry);$("saveEntryBtn").textContent=entry?"수정 저장":"기록 저장";state.handwriting.draft=entry?.inputMethod==="handwriting"?{rawOcrText:entry.rawOcrText||"",suggestedText:entry.suggestedText||"",confirmedText:entry.confirmedText||entry.quoteText||"",existing:true}:null;openDialog("recordDialog")}
async function saveEntry(){
  const quote=safeText($("entryQuote").value),thought=safeText($("entryThought").value),locator=safeText($("entryLocator").value);if(!quote&&!thought)return toast("책의 문장이나 내 생각 중 하나는 남겨주세요.");const editing=state.editingEntryId?state.readingEntries.find(e=>e.id===state.editingEntryId):null,sourceId=editing?.sourceId||state.activeSession?.sourceId||state.detailBookId||state.currentBookId;if(!sourceId)return toast("연결할 책을 찾지 못했습니다.");const cycle=editing?.cycleId?state.readingCycles.find(c=>c.id===editing.cycleId):ensureCycle(sourceId),d=state.handwriting.draft,entry=editing||{id:uid(),sourceId,cycleId:cycle?.id||null,sessionId:state.activeSession?.id||null,createdAt:nowIso()};Object.assign(entry,{locator,quoteText:quote,thought,inputMethod:d?"handwriting":"typing",rawOcrText:d?.rawOcrText||entry.rawOcrText||"",suggestedText:d?.suggestedText||entry.suggestedText||"",confirmedText:d?.confirmedText||quote,updatedAt:nowIso()});
  if(thought){let fragmentId=entry.linkedFragmentId||uid();entry.linkedFragmentId=fragmentId;const old=state.fragments.find(f=>f.id===fragmentId),fragment={id:fragmentId,type:"source",sourceId,externalText:quote,locator,thought,threadIds:old?.threadIds||[],date:localDate(entry.createdAt),createdAt:old?.createdAt||entry.createdAt,updatedAt:nowIso()},fi=state.fragments.findIndex(f=>f.id===fragmentId);if(fi>=0)state.fragments[fi]=fragment;else state.fragments.push(fragment);await cloudSet("fragments",fragmentId,fragment,{silent:true})}else if(entry.linkedFragmentId){await cloudDelete("fragments",entry.linkedFragmentId);state.fragments=state.fragments.filter(f=>f.id!==entry.linkedFragmentId);entry.linkedFragmentId=null}
  const i=state.readingEntries.findIndex(e=>e.id===entry.id);if(i>=0)state.readingEntries[i]=entry;else state.readingEntries.push(entry);await cloudSet("readingEntries",entry.id,entry,{silent:true});if(d?.imageBlob&&!d.existing)await saveHandwritingFiles(entry);await cacheSnapshot();closeDialog("recordDialog");state.editingEntryId=null;state.handwriting.draft=null;renderTimeline();if(state.detailBookId)renderBookDetail();toast(d?.imageBlob?"기록했습니다. 필사 이미지는 동기화 중입니다. ✍":"기록했습니다 🌱")
}
async function deleteCurrentEntry(){const e=state.readingEntries.find(x=>x.id===state.editingEntryId);if(!e)return;if(!confirm("이 독서 기록을 삭제할까요?"))return;state.readingEntries=state.readingEntries.filter(x=>x.id!==e.id);await cloudDelete("readingEntries",e.id);if(e.linkedFragmentId&&confirm("연결된 생각의 텃밭 생각도 함께 삭제할까요?")){state.fragments=state.fragments.filter(f=>f.id!==e.linkedFragmentId);await cloudDelete("fragments",e.linkedFragmentId)}closeDialog("recordDialog");renderAll();toast("기록을 삭제했습니다.")}

function drawStrokeSegment(ctx,s,a,b){if(!a||!b)return;ctx.save();ctx.lineCap="round";ctx.lineJoin="round";ctx.globalCompositeOperation=s.erase?"destination-out":"source-over";ctx.strokeStyle="#171a16";const pa=.58+Math.max(.06,Math.min(1,a.p||.5))*.92,pb=.58+Math.max(.06,Math.min(1,b.p||.5))*.92;ctx.lineWidth=s.erase?22:s.width*(pa+pb)/2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}
function setupHandwriting(){
  const canvas=$("writingCanvas"),paper=$("writingPaper"),ctx=canvas.getContext("2d"),resize=()=>{const r=paper.getBoundingClientRect(),dpr=Math.max(1,Math.min(3,devicePixelRatio||1));state.handwriting.dpr=dpr;canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);redrawWriting()};new ResizeObserver(resize).observe(paper);const pos=e=>{const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,p:e.pressure>0?e.pressure:.5}};
  canvas.addEventListener("pointerdown",e=>{if(e.pointerType==="touch")return;e.preventDefault();canvas.setPointerCapture?.(e.pointerId);const s={erase:state.handwriting.eraser,width:state.handwriting.width,points:[pos(e)]};state.handwriting.current=s;state.handwriting.strokes.push(s)},{passive:false});
  canvas.addEventListener("pointermove",e=>{const s=state.handwriting.current;if(!s||e.pointerType==="touch")return;e.preventDefault();const list=e.getCoalescedEvents?.()||[e];for(const ce of list){const p=pos(ce),last=s.points.at(-1);if(!last||Math.hypot(p.x-last.x,p.y-last.y)>.65){s.points.push(p);drawStrokeSegment(ctx,s,last,p)}}$("writingHint").classList.toggle("hidden",state.handwriting.strokes.some(x=>!x.erase&&x.points.length))},{passive:false});
  const end=()=>{state.handwriting.current=null};canvas.addEventListener("pointerup",end);canvas.addEventListener("pointercancel",end);canvas.addEventListener("lostpointercapture",end);
}
function redrawWriting(targetCtx=null,targetCanvas=null){const canvas=targetCanvas||$("writingCanvas"),ctx=targetCtx||canvas.getContext("2d"),dpr=targetCanvas?1:state.handwriting.dpr;if(!targetCanvas){ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.restore();ctx.setTransform(dpr,0,0,dpr,0,0)}for(const s of state.handwriting.strokes){if(!s.points.length)continue;for(let i=1;i<s.points.length;i++)drawStrokeSegment(ctx,s,s.points[i-1],s.points[i])}$("writingHint").classList.toggle("hidden",state.handwriting.strokes.some(s=>!s.erase&&s.points.length))}
function openHandwriting(){const sourceId=state.activeSession?.sourceId||state.detailBookId||state.currentBookId,s=sourceById(sourceId);$("handwritingBookTitle").textContent=s?.title||"필사";$("handwritingMeta").textContent=$("entryLocator").value||"";state.handwriting.strokes=[];state.handwriting.current=null;state.handwriting.draft=null;closeDialog("recordDialog");openLayer("handwritingLayer");setTimeout(()=>redrawWriting(),80)}
async function buildHandwritingDraft(){
  const ink=state.handwriting.strokes.filter(s=>!s.erase&&s.points.length);if(!ink.length){toast("먼저 필사해주세요.");return null}
  const pad=28;let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;
  for(const s of ink)for(const p of s.points){if(p.x<minX)minX=p.x;if(p.y<minY)minY=p.y;if(p.x>maxX)maxX=p.x;if(p.y>maxY)maxY=p.y}
  minX=Math.max(0,minX-pad);minY=Math.max(0,minY-pad);const paper=$("writingPaper").getBoundingClientRect();maxX=Math.min(paper.width,maxX+pad);maxY=Math.min(paper.height,maxY+pad);
  const w=Math.max(1,Math.ceil(maxX-minX)),h=Math.max(1,Math.ceil(maxY-minY)),scale=2,out=document.createElement("canvas");out.width=w*scale;out.height=h*scale;const o=out.getContext("2d");o.fillStyle="#fff";o.fillRect(0,0,out.width,out.height);o.save();o.scale(scale,scale);o.translate(-minX,-minY);redrawWriting(o,out);o.restore();const imageBlob=await new Promise(r=>out.toBlob(r,"image/webp",.84));let raw="";if("TextDetector" in window){try{const det=new TextDetector(),found=await det.detect(out);raw=found.map(x=>x.rawValue||"").filter(Boolean).join("\n")}catch{}}return {imageBlob,rawOcrText:raw,suggestedText:raw,confirmedText:raw};
}
async function convertHandwriting(){const d=await buildHandwritingDraft();if(!d)return;state.handwriting.draft=d;state.handwriting.strokes=[];state.handwriting.current=null;$("ocrConfirmedText").value=d.confirmedText;$("ocrRawText").textContent=d.rawOcrText||"이 기기에서는 브라우저 OCR을 사용할 수 없습니다. 실제 OCR 서버 연결은 다음 개발 단계에서 붙입니다.";$("ocrNotice").textContent=d.rawOcrText?"기기에서 감지한 텍스트입니다. 원문과 비교해 수정한 뒤 확정해주세요.":"필사 원본 이미지는 준비됐습니다. 텍스트를 직접 확인·수정해 확정할 수 있습니다.";closeLayer("handwritingLayer");openDialog("ocrDialog")}
function confirmOcr(){const text=safeText($("ocrConfirmedText").value);if(!text)return toast("확정할 문장을 입력해주세요.");state.handwriting.draft.confirmedText=text;state.handwriting.draft.suggestedText=text;$("entryQuote").value=text;closeDialog("ocrDialog");openDialog("recordDialog")}

function normalizeGenre(raw=""){const x=raw.toLowerCase();if(/소설|문학/.test(x))return "소설";if(/에세이/.test(x))return "에세이";if(/인문|철학/.test(x))return "인문·철학";if(/사회|정치/.test(x))return "사회·정치";if(/역사/.test(x))return "역사";if(/심리/.test(x))return "심리";if(/경제|경영/.test(x))return "경제·경영";if(/과학|기술|컴퓨터/.test(x))return "과학·기술";if(/예술|문화/.test(x))return "예술·문화";if(/자기계발/.test(x))return "자기계발";if(/육아|교육/.test(x))return "육아·교육";return "기타"}
function getThoughtGardenApiKeys(){try{return JSON.parse(localStorage.getItem("thoughtGarden_apiKeys")||"{}")}catch{return {}}}
async function googleBooksSearch(q){try{const keys=getThoughtGardenApiKeys(),key=keys.youtube||keys.google||keys.googleBooks||keys.googleApiKey||"",url=new URL("https://www.googleapis.com/books/v1/volumes");url.searchParams.set("q",q);url.searchParams.set("maxResults","20");if(key)url.searchParams.set("key",key);const r=await fetch(url);if(!r.ok)return [];const j=await r.json();return (j.items||[]).map(item=>{const v=item.volumeInfo||{},isbn=(v.industryIdentifiers||[]).find(x=>x.type==="ISBN_13")?.identifier||(v.industryIdentifiers||[])[0]?.identifier||"";return {title:safeText(v.title),creator:safeText((v.authors||[]).join(", ")),publisher:safeText(v.publisher),image:(v.imageLinks?.thumbnail||v.imageLinks?.smallThumbnail||"").replace(/^http:/,"https:"),isbn13:isbn,categoryName:safeText((v.categories||[]).join(" > ")),pubDate:v.publishedDate||"",externalLink:v.infoLink||"",provider:"Google Books"}}).filter(x=>x.title)}catch{return []}}
function dedupeBookResults(items){const seen=new Set();return items.filter(x=>{const key=(String(x.isbn13||"").replace(/\D/g,"")||`${x.title}|${x.creator}`).toLowerCase();if(seen.has(key))return false;seen.add(key);return true})}
function openBookSearch(){openDialog("bookSearchDialog");setTimeout(()=>$("bookSearchInput").focus(),50)}
async function runBookSearch(){const q=safeText($("bookSearchInput").value);if(!q)return;const box=$("bookSearchResults");box.innerHTML=`<div class="helper">검색 중…</div>`;const local=state.sources.filter(s=>`${s.title} ${s.creator}`.toLowerCase().includes(q.toLowerCase())).slice(0,6);let api=[];try{const r=await fetch(`${BOOK_SEARCH_PROXY}?q=${encodeURIComponent(q)}`),j=await r.json();if(j.ok)api=(j.items||[]).map(x=>({title:safeText(x.title),creator:safeText(x.author),publisher:safeText(x.publisher),image:x.cover||"",isbn13:x.isbn13||x.isbn||"",categoryName:safeText(x.categoryName),pubDate:x.pubDate||"",externalLink:x.link||"",provider:"Aladin"}))}catch(err){console.warn(err)}if(api.length<8){const google=await googleBooksSearch(q);api=dedupeBookResults([...api,...google])}box.innerHTML=(local.length?`<div class="eyebrow" style="margin:10px 0 4px">이미 내 서재에 있음</div>${local.map(s=>bookSearchRow(s,true)).join("")}`:"")+(api.length?`<div class="eyebrow" style="margin:14px 0 4px">검색 결과</div>${api.map((x,i)=>bookSearchRow({...x,_index:i},false)).join("")}`:`<div class="empty-card">검색 결과가 없습니다.</div>`);state.bookApiResults=api}
function bookSearchRow(x,existing){return `<div class="search-book-row">${x.image?`<img src="${esc(x.image)}" alt="">`:`<div style="width:48px;height:68px;background:var(--panel2);border-radius:7px;display:grid;place-items:center">📕</div>`}<div><h3>${esc(x.title)}</h3><p>${esc(x.creator||"")}${x.publisher?` · ${esc(x.publisher)}`:""}</p></div><button class="btn ${existing?"soft":"primary"}" ${existing?`data-open-existing-book="${esc(x.id)}"`:`data-add-api-book="${x._index}"`} type="button">${existing?"열기":"추가"}</button></div>`}
async function addApiBook(index){const x=state.bookApiResults?.[index];if(!x)return;const dup=x.isbn13&&state.sources.find(s=>String(s.isbn13||"").replace(/\D/g,"")===String(x.isbn13).replace(/\D/g,""));if(dup){closeDialog("bookSearchDialog");openBookDetail(dup.id);toast("이미 등록된 책을 열었습니다.");return}const s={id:uid(),type:"book",status:"active",title:x.title,creator:x.creator,platform:"",image:x.image,isbn13:x.isbn13,provider:x.provider,externalLink:x.externalLink,rawCategories:x.categoryName?[x.categoryName]:[],primaryGenre:normalizeGenre(x.categoryName),publisher:x.publisher,pubDate:x.pubDate,createdAt:nowIso(),updatedAt:nowIso()};state.sources.push(s);await cloudSet("sources",s.id,s);closeDialog("bookSearchDialog");openProfile(s.id);renderAll()}

function openProfile(sourceId){const p=getProfile(sourceId),s=sourceById(sourceId);$("profileSourceId").value=sourceId;$("profileDialogTitle").textContent=s?.title||"읽기 설정";$("profileStatus").value=p?.status||"reading";$("profileFormat").value=p?.format||"ebook";$("profileService").value=p?.service||"other";$("profileLocator").value=p?.currentLocator||"";openDialog("profileDialog")}
async function saveProfile(){const id=$("profileSourceId").value,p=ensureProfile(id);Object.assign(p,{status:$("profileStatus").value,format:$("profileFormat").value,service:$("profileService").value,currentLocator:safeText($("profileLocator").value),updatedAt:nowIso()});if(!p.startedAt&&p.status==="reading")p.startedAt=nowIso();if(p.status==="completed"&&!p.completedAt)p.completedAt=nowIso();await cloudSet("readingProfiles",p.id,p);const s=sourceById(id);if(s){s.status=p.status==="completed"?"done":"active";s.updatedAt=nowIso();await cloudSet("sources",s.id,s,{silent:true})}closeDialog("profileDialog");state.currentBookId=id;localStorage.setItem(CURRENT_BOOK_KEY,id);renderAll();if(state.detailBookId===id)renderBookDetail()}
function openComplete(sourceId){state.detailBookId=sourceId;const s=sourceById(sourceId),m=bookMetrics(sourceId),c=state.readingCycles.find(x=>x.sourceId===sourceId&&!x.completedAt)||ensureCycle(sourceId);$("completeBookTitle").textContent=`${s?.title||"이 책"} 완독`;$("completeSummary").innerHTML=`${c.startedAt?displayDateFull(c.startedAt):""}<br><b>${fmtMinutes(m.mins)}</b> · ${m.days}일 동안 읽음`;$("finalReflection").value=c.finalReflection||"";$("oneLineReflection").value=c.oneLineReflection||"";$("rereadWanted").checked=!!c.rereadWanted;openDialog("completeDialog")}
async function saveComplete(){const id=state.detailBookId,p=ensureProfile(id),c=state.readingCycles.find(x=>x.sourceId===id&&!x.completedAt)||ensureCycle(id),at=nowIso();Object.assign(c,{completedAt:at,finalReflection:safeText($("finalReflection").value),oneLineReflection:safeText($("oneLineReflection").value),rereadWanted:$("rereadWanted").checked,updatedAt:at});Object.assign(p,{status:"completed",completedAt:at,updatedAt:at});const s=sourceById(id);if(s){s.status="done";s.updatedAt=at}await Promise.all([cloudSet("readingCycles",c.id,c,{silent:true}),cloudSet("readingProfiles",p.id,p,{silent:true}),s?cloudSet("sources",s.id,s,{silent:true}):Promise.resolve()]);closeDialog("completeDialog");renderAll();if(state.detailBookId)renderBookDetail();toast("완독을 기록했습니다. ◉")}

function renderTimelineBookOptions(){const sel=$("timelineBookFilter"),v=sel.value;sel.innerHTML=`<option value="">전체 책</option>`+state.sources.slice().sort((a,b)=>a.title.localeCompare(b.title,"ko")).map(s=>`<option value="${esc(s.id)}">${esc(s.title)}</option>`).join("");sel.value=v}
function timelineEvents(bookId=""){const linked=new Set(state.readingEntries.map(e=>e.linkedFragmentId).filter(Boolean)),events=[];for(const s of state.readingSessions.filter(x=>x.endedAt&&(!bookId||x.sourceId===bookId)))events.push({type:"session",date:s.startedAt,session:s,entries:state.readingEntries.filter(e=>e.sessionId===s.id)});for(const e of state.readingEntries.filter(e=>!e.sessionId&&(!bookId||e.sourceId===bookId)))events.push({type:"entry",date:e.createdAt,entry:e});for(const f of state.fragments.filter(f=>f.sourceId&&sourceById(f.sourceId)&&!linked.has(f.id)&&(!bookId||f.sourceId===bookId)))events.push({type:"legacy",date:f.date||f.createdAt,fragment:f});for(const c of state.readingCycles.filter(c=>c.completedAt&&(!bookId||c.sourceId===bookId)))events.push({type:"complete",date:c.completedAt,cycle:c});return events.sort((a,b)=>new Date(b.date)-new Date(a.date))}
function entryMatches(e,filter){if(filter==="all")return true;if(filter==="quote")return !!safeText(e.quoteText||e.confirmedText);if(filter==="handwriting")return e.inputMethod==="handwriting";if(filter==="thought")return !!safeText(e.thought);return true}
function renderEntryHtml(e,{legacy=false}={}){const quote=safeText(e.quoteText||e.confirmedText||e.externalText),thought=safeText(e.thought);return `<div class="timeline-entry" ${!legacy?`data-edit-entry="${esc(e.id)}"`:""}>${e.locator?`<div class="entry-locator">${esc(e.locator)}</div>`:""}${e.handwritingImageUrl?`<img class="handwriting-preview" src="${esc(e.handwritingImageUrl)}" alt="필사 원본">`:e.inputMethod==="handwriting"&&e.handwritingPending?`<div class="notice">✍ 필사 원본 동기화 중</div>`:""}${quote?`<div class="entry-quote">${esc(quote)}</div>`:""}${thought?`<div class="entry-thought">${esc(thought)}</div>`:""}${legacy?`<span class="legacy-badge">생각의 텃밭에서 남긴 기록</span>`:""}</div>`}
function renderEvent(ev,filter="all"){
  if(ev.type==="session"){const s=sourceById(ev.session.sourceId),entries=ev.entries.filter(e=>entryMatches(e,filter));if(filter!=="all"&&!entries.length)return "";return `<div class="timeline-card"><article class="timeline-session"><div class="timeline-session-head">${s?.image?`<img class="timeline-thumb" src="${esc(s.image)}" alt="">`:`<div class="timeline-thumb"></div>`}<div><h3>${esc(s?.title||"책")}</h3><p>${timeText(ev.session.startedAt)}${ev.session.endedAt?` – ${timeText(ev.session.endedAt)}`:""} · ${fmtMinutes(ev.session.finalDurationMinutes)} · ${esc(SERVICE_LABELS[ev.session.service]||"")}</p></div></div>${entries.map(e=>renderEntryHtml(e)).join("")}${ev.session.sessionNote&&filter==="all"?`<div class="session-note">“${esc(ev.session.sessionNote)}”</div>`:""}</article></div>`}
  if(ev.type==="entry"){if(!entryMatches(ev.entry,filter))return "";const s=sourceById(ev.entry.sourceId);return `<div class="timeline-card"><article class="timeline-session"><div class="timeline-session-head"><div><h3>${esc(s?.title||"책")}</h3><p>독서 기록</p></div></div>${renderEntryHtml(ev.entry)}</article></div>`}
  if(ev.type==="legacy"){const f=ev.fragment,e={sourceId:f.sourceId,locator:f.locator,externalText:f.externalText,thought:f.thought};if(filter==="handwriting")return "";if(filter==="quote"&&!safeText(f.externalText))return "";if(filter==="thought"&&!safeText(f.thought))return "";const s=sourceById(f.sourceId);return `<div class="timeline-card"><article class="timeline-session"><div class="timeline-session-head"><div><h3>${esc(s?.title||"책")}</h3><p>예전 독서 기록</p></div></div>${renderEntryHtml(e,{legacy:true})}</article></div>`}
  if(ev.type==="complete"&&filter==="all"){const c=ev.cycle,s=sourceById(c.sourceId),m=bookMetrics(c.sourceId);return `<div class="timeline-card"><div class="completion-event"><div class="complete-mark">◉</div><h3>${esc(s?.title||"책")} 완독</h3><p>${c.startedAt?`${displayDateFull(c.startedAt)} → `:""}${displayDateFull(c.completedAt)}<br>${fmtMinutes(m.mins)} · ${m.days}일 독서</p>${c.oneLineReflection?`<div class="entry-thought">${esc(c.oneLineReflection)}</div>`:""}</div></div>`}return "";
}
function renderTimelineHtml({bookId="",embedded=false}={}){const filter=embedded?"all":state.timelineFilter,events=timelineEvents(bookId||(!embedded?$("timelineBookFilter")?.value||"":"")),groups=new Map();for(const ev of events){const html=renderEvent(ev,filter);if(!html)continue;const d=localDate(ev.date);if(!groups.has(d))groups.set(d,[]);groups.get(d).push(html)}if(!groups.size)return `<div class="empty-card">아직 보여줄 독서 기록이 없습니다.</div>`;return [...groups.entries()].map(([d,items])=>`<section class="day-group"><div class="day-title">${displayDate(`${d}T12:00:00`)}</div>${items.join("")}</section>`).join("")}
function renderTimeline(){$("timelineList").innerHTML=renderTimelineHtml()}

function rangeStart(range){const n=new Date();if(range==="week"){const d=n.getDay()||7;n.setHours(0,0,0,0);n.setDate(n.getDate()-d+1);return n}if(range==="month")return new Date(n.getFullYear(),n.getMonth(),1);if(range==="year")return new Date(n.getFullYear(),0,1);return new Date(0)}
function sessionsInRange(){const st=rangeStart(state.statsRange);return state.readingSessions.filter(s=>s.endedAt&&new Date(s.startedAt)>=st)}
function entriesInRange(){const st=rangeStart(state.statsRange);return state.readingEntries.filter(e=>new Date(e.createdAt)>=st)}
function renderStats(){const ss=sessionsInRange(),es=entriesInRange(),mins=ss.reduce((a,b)=>a+(Number(b.finalDurationMinutes)||0),0),days=new Set(ss.map(s=>localDate(s.startedAt))).size,complete=state.readingCycles.filter(c=>c.completedAt&&new Date(c.completedAt)>=rangeStart(state.statsRange)).length;$("statsSummary").innerHTML=`<div class="stat-card"><small>독서시간</small><strong>${fmtMinutes(mins)}</strong></div><div class="stat-card"><small>독서한 날</small><strong>${days}일</strong></div><div class="stat-card"><small>세션</small><strong>${ss.length}회</strong></div><div class="stat-card"><small>완독</small><strong>${complete}권</strong></div>`;const daily=buildDailySeries(ss),weekday=[0,1,2,3,4,5,6].map(d=>({label:["일","월","화","수","목","금","토"][d],value:ss.filter(s=>new Date(s.startedAt).getDay()===d).reduce((a,b)=>a+(+b.finalDurationMinutes||0),0)})),timeBuckets=[{label:"아침",test:h=>h>=5&&h<11},{label:"낮",test:h=>h>=11&&h<17},{label:"저녁",test:h=>h>=17&&h<22},{label:"심야",test:h=>h>=22||h<5}].map(b=>({label:b.label,value:ss.filter(s=>b.test(new Date(s.startedAt).getHours())).reduce((a,x)=>a+(+x.finalDurationMinutes||0),0)})),genres=genreSeries(ss),activity=[{label:"문장",value:es.filter(e=>safeText(e.quoteText||e.confirmedText)).length},{label:"필사",value:es.filter(e=>e.inputMethod==="handwriting").length},{label:"생각",value:es.filter(e=>safeText(e.thought)).length}];$("statsCharts").innerHTML=chartCard("독서시간 추이","시간의 흐름에 따라 읽은 분량이 어떻게 달라졌는지 봅니다.",daily,"분")+hbarCard("요일별 독서 패턴","어떤 요일에 책을 더 자주 붙잡는지 봅니다.",weekday,"분")+hbarCard("시간대별 독서","읽기가 잘 시작되는 시간대를 봅니다.",timeBuckets,"분")+hbarCard("장르 분포","독서시간 기준입니다.",genres,"분")+hbarCard("남긴 기록","문장 · 필사 · 생각이 얼마나 쌓였는지 봅니다.",activity,"개")+`<div class="chart-card"><h3>Thought Garden으로 이어진 생각</h3><p>책을 읽다 생긴 내 생각만 공유합니다.</p><strong style="font-family:var(--serif);font-size:1.5rem">${es.filter(e=>e.linkedFragmentId).length}개</strong></div>`}
function buildDailySeries(ss){const out=[],days=state.statsRange==="week"?7:state.statsRange==="month"?Math.min(31,new Date().getDate()):12;if(state.statsRange==="year"||state.statsRange==="all"){const n=new Date();for(let i=days-1;i>=0;i--){const d=new Date(n.getFullYear(),n.getMonth()-i,1),ym=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;out.push({label:`${d.getMonth()+1}월`,value:ss.filter(s=>localDate(s.startedAt).startsWith(ym)).reduce((a,b)=>a+(+b.finalDurationMinutes||0),0)})}}else{const n=new Date();for(let i=days-1;i>=0;i--){const d=new Date(n);d.setDate(n.getDate()-i);const key=d.toLocaleDateString("en-CA");out.push({label:`${d.getMonth()+1}/${d.getDate()}`,value:ss.filter(s=>localDate(s.startedAt)===key).reduce((a,b)=>a+(+b.finalDurationMinutes||0),0)})}}return out}
function genreSeries(ss){const map={};for(const s of ss){const book=sourceById(s.sourceId),g=book?.primaryGenre||"기타";map[g]=(map[g]||0)+(+s.finalDurationMinutes||0)}return Object.entries(map).map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value)}
function chartCard(title,desc,data,unit){const max=Math.max(1,...data.map(x=>x.value));return `<section class="chart-card"><h3>${title}</h3><p>${desc}</p><div class="bar-chart">${data.map(x=>`<div class="bar-col" title="${esc(x.label)} ${x.value}${unit}"><span style="height:${Math.max(2,x.value/max*120)}px"></span><small>${esc(x.label)}</small></div>`).join("")}</div></section>`}
function hbarCard(title,desc,data,unit){const max=Math.max(1,...data.map(x=>x.value));return `<section class="chart-card"><h3>${title}</h3><p>${desc}</p><div class="hbar-list">${data.map(x=>`<div class="hbar-row"><span>${esc(x.label)}</span><div class="hbar-track"><div class="hbar-fill" style="width:${x.value/max*100}%"></div></div><span class="hbar-value">${x.value}${unit}</span></div>`).join("")}</div></section>`}

function searchRecords(q){q=q.toLowerCase();const results=[];for(const e of state.readingEntries){const s=sourceById(e.sourceId),text=`${s?.title||""} ${s?.creator||""} ${e.locator||""} ${e.quoteText||""} ${e.confirmedText||""} ${e.thought||""}`.toLowerCase();if(text.includes(q))results.push({kind:"entry",date:e.createdAt,e,s})}for(const f of state.fragments){const s=sourceById(f.sourceId);if(!s)continue;const text=`${s.title} ${s.creator||""} ${f.externalText||""} ${f.thought||""} ${f.locator||""}`.toLowerCase();if(text.includes(q))results.push({kind:"legacy",date:f.date||f.createdAt,f,s})}return results.sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,100)}
function renderSearch(){const q=safeText($("globalSearchInput").value);if(!q){$("globalSearchResults").innerHTML=`<div class="helper">검색어를 입력하세요.</div>`;return}const rr=searchRecords(q);$("globalSearchResults").innerHTML=rr.length?rr.map(r=>`<div class="search-result-row"><div><h3>${esc(r.s?.title||"책")}</h3><p>${displayDateFull(r.date)}${(r.e?.locator||r.f?.locator)?` · ${esc(r.e?.locator||r.f?.locator)}`:""}</p><p style="margin-top:5px;color:var(--text)">${esc((r.e?.quoteText||r.e?.thought||r.f?.externalText||r.f?.thought||"").slice(0,120))}</p></div></div>`).join(""):`<div class="empty-card">검색 결과가 없습니다.</div>`}
function openPathDialog(){$("pathTitle").value="";$("pathDescription").value="";$("pathBookChoices").innerHTML=state.sources.map(s=>`<label class="choice-row"><input type="checkbox" value="${esc(s.id)}"><span>${esc(s.title)}<small style="display:block;color:var(--muted)">${esc(s.creator||"")}</small></span></label>`).join("");openDialog("pathDialog")}
async function savePath(){const title=safeText($("pathTitle").value);if(!title)return toast("Path 이름을 적어주세요.");const sourceIds=$$("#pathBookChoices input:checked").map(x=>x.value),p={id:uid(),title,description:safeText($("pathDescription").value),sourceIds,createdAt:nowIso(),updatedAt:nowIso()};state.readingPaths.push(p);await cloudSet("readingPaths",p.id,p);closeDialog("pathDialog");renderPaths();toast("Reading Path를 만들었습니다.")}

function buildPrintData(scopeBookId=""){return timelineEvents(scopeBookId)}
function openExport(bookId=""){state.exportBookId=bookId||"";$("exportScope").value=bookId?"currentBook":"all";openDialog("exportDialog")}
function doPrint(){const bookId=$("exportScope").value==="currentBook"?(state.exportBookId||state.detailBookId||state.currentBookId):"",events=buildPrintData(bookId),books=bookId?[sourceById(bookId)]:state.sources;let html=`<section class="print-cover"><div style="font-size:26pt">📖</div><h1>독서의 정원</h1><p>${bookId?esc(sourceById(bookId)?.title||""):"나의 독서 기록"}</p><p>${displayDateFull(nowIso())}</p></section>`;if(bookId)html+=printBookSection(bookId,events);else for(const s of books){const es=events.filter(e=>(e.session?.sourceId||e.entry?.sourceId||e.fragment?.sourceId||e.cycle?.sourceId)===s.id);if(es.length)html+=printBookSection(s.id,es)}$("printRoot").innerHTML=html;closeDialog("exportDialog");setTimeout(()=>window.print(),80)}
function printBookSection(id,events){const s=sourceById(id),m=bookMetrics(id);let html=`<section class="print-section"><div class="print-book-head">${s?.image?`<img src="${esc(s.image)}" alt="">`:""}<div><h2>${esc(s?.title||"책")}</h2><div>${esc(s?.creator||"")}</div><div class="print-meta">총 독서시간 ${fmtMinutes(m.mins)} · 독서일 ${m.days}일 · 세션 ${m.sessions}회</div></div></div>`,groups=new Map();for(const ev of events){const d=localDate(ev.date);if(!groups.has(d))groups.set(d,[]);groups.get(d).push(ev)}for(const [d,items] of groups){html+=`<div class="print-day">${displayDateFull(`${d}T12:00:00`)}</div>`;for(const ev of items){if(ev.type==="session"&&$("printSession").checked)html+=`<div class="print-session">${timeText(ev.session.startedAt)} – ${timeText(ev.session.endedAt)} · ${fmtMinutes(ev.session.finalDurationMinutes)}${ev.session.sessionNote?`<br>${esc(ev.session.sessionNote)}`:""}</div>`;const entries=ev.type==="session"?ev.entries:ev.type==="entry"?[ev.entry]:[];for(const e of entries)html+=printEntry(e);if(ev.type==="legacy")html+=printEntry({locator:ev.fragment.locator,quoteText:ev.fragment.externalText,thought:ev.fragment.thought});if(ev.type==="complete")html+=`<div class="print-complete">◉ 완독<br>${esc(ev.cycle.oneLineReflection||ev.cycle.finalReflection||"")}</div>`}}html+=`</section>`;return html}
function printEntry(e){const quote=safeText(e.quoteText||e.confirmedText),thought=safeText(e.thought);if(!quote&&!thought)return "";return `<div class="print-entry">${e.locator?`<div class="print-meta">${esc(e.locator)}</div>`:""}${$("printHandwriting").checked&&e.handwritingImageUrl?`<img class="print-handwriting" src="${esc(e.handwritingImageUrl)}" alt="필사">`:""}${$("printQuote").checked&&quote?`<div class="print-quote">${esc(quote)}</div>`:""}${$("printThought").checked&&thought?`<div class="print-thought">${esc(thought)}</div>`:""}</div>`}
function downloadBlob(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
function backupJson(){const data={version:1,exportedAt:nowIso(),sources:state.sources,readingProfiles:state.readingProfiles,readingCycles:state.readingCycles,readingSessions:state.readingSessions,readingEntries:state.readingEntries,readingPaths:state.readingPaths};downloadBlob(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),`reading-garden-backup-${localDate()}.json`)}
async function restoreJson(file){try{const data=JSON.parse(await file.text());if(!confirm("백업 데이터를 현재 독서의 정원에 합칠까요? 같은 ID는 백업 내용으로 갱신됩니다."))return;for(const name of ["sources",...COLLECTIONS])for(const item of Array.isArray(data[name])?data[name]:[]){const arr=state[name],i=arr.findIndex(x=>x.id===item.id);if(i>=0)arr[i]=item;else arr.push(item);await cloudSet(name,item.id,item,{silent:true})}await cacheSnapshot();renderAll();toast("JSON 백업을 복원했습니다.")}catch(err){toast(`복원 실패: ${err.message}`)}}

function bindEvents(){
  document.addEventListener("click",async e=>{
    const nav=e.target.closest("[data-view-target]");if(nav)return setView(nav.dataset.viewTarget);const close=e.target.closest("[data-close-dialog]");if(close)return closeDialog(close.dataset.closeDialog);const layer=e.target.closest("[data-close-layer]");if(layer)return closeLayer(layer.dataset.closeLayer);const start=e.target.closest("[data-start-book]");if(start){if(!$("bookDetail").classList.contains("hidden"))closeLayer("bookDetail");return startSession(start.dataset.startBook)}if(e.target.closest("[data-resume-session]"))return openSession();if(e.target.closest("[data-abandon-session]"))return openEndSession();if(e.target.closest("[data-open-book-picker]")){renderBookPicker();return openDialog("bookPickerDialog")}if(e.target.closest("[data-open-book-search]"))return openBookSearch();const pick=e.target.closest("[data-pick-book]");if(pick){setCurrentBook(pick.dataset.pickBook);closeDialog("bookPickerDialog");return}const ob=e.target.closest("[data-open-book]");if(ob)return openBookDetail(ob.dataset.openBook);const os=e.target.closest("[data-open-existing-book]");if(os){closeDialog("bookSearchDialog");return openBookDetail(os.dataset.openExistingBook)}const api=e.target.closest("[data-add-api-book]");if(api)return addApiBook(Number(api.dataset.addApiBook));const st=e.target.closest("[data-library-status]");if(st){state.libraryStatus=st.dataset.libraryStatus;return renderLibrary()}const lm=e.target.closest("[data-library-mode]");if(lm){state.libraryMode=lm.dataset.libraryMode;$$('[data-library-mode]').forEach(b=>b.classList.toggle('on',b===lm));return renderLibrary()}const ef=e.target.closest("[data-entry-filter]");if(ef){state.timelineFilter=ef.dataset.entryFilter;$$('[data-entry-filter]').forEach(b=>b.classList.toggle('on',b===ef));return renderTimeline()}const rg=e.target.closest("[data-range]");if(rg){state.statsRange=rg.dataset.range;$$('[data-range]').forEach(b=>b.classList.toggle('on',b===rg));return renderStats()}const dt=e.target.closest("[data-detail-tab]");if(dt){state.detailTab=dt.dataset.detailTab;return renderBookDetail()}const ep=e.target.closest("[data-edit-profile]");if(ep)return openProfile(ep.dataset.editProfile);const cb=e.target.closest("[data-complete-book]");if(cb)return openComplete(cb.dataset.completeBook);const pb=e.target.closest("[data-print-book]");if(pb)return openExport(pb.dataset.printBook);const ee=e.target.closest("[data-edit-entry]");if(ee){const entry=state.readingEntries.find(x=>x.id===ee.dataset.editEntry);if(entry)return openRecord({entry,fromSession:false})}
  });
  $("addBookBtn").onclick=openBookSearch;$("runBookSearchBtn").onclick=runBookSearch;$("bookSearchInput").addEventListener("keydown",e=>{if(e.key==="Enter")runBookSearch()});$("librarySearch").addEventListener("input",renderLibrary);$("timelineBookFilter").addEventListener("change",renderTimeline);$("openSettings").onclick=()=>openDialog("settingsDialog");$("newPathBtn").onclick=openPathDialog;$("savePathBtn").onclick=savePath;$("bookMoreBtn").onclick=()=>$("bookMoreMenu")?.classList.toggle("hidden");$("sessionBackBtn").onclick=()=>{closeLayer("sessionLayer");renderRead()};$("openRecordBtn").onclick=()=>openRecord({fromSession:true});$("pauseSessionBtn").onclick=togglePause;$("endSessionBtn").onclick=openEndSession;$("finishSessionBtn").onclick=finishSession;$("saveEntryBtn").onclick=saveEntry;$("deleteEntryBtn").onclick=deleteCurrentEntry;$("openHandwritingBtn").onclick=openHandwriting;$("closeHandwritingBtn").onclick=()=>{closeLayer("handwritingLayer");openDialog("recordDialog")};
  $$('[data-pen-width]').forEach(b=>b.onclick=()=>{state.handwriting.width=Number(b.dataset.penWidth);state.handwriting.eraser=false;$$('[data-pen-width]').forEach(x=>x.classList.toggle('on',x===b));$("eraserBtn").classList.remove("on")});$("eraserBtn").onclick=()=>{state.handwriting.eraser=!state.handwriting.eraser;$("eraserBtn").classList.toggle("on",state.handwriting.eraser);if(state.handwriting.eraser)$$('[data-pen-width]').forEach(x=>x.classList.remove('on'))};$("undoStrokeBtn").onclick=()=>{state.handwriting.strokes.pop();redrawWriting()};$("convertHandwritingBtn").onclick=convertHandwriting;$("redoHandwritingBtn").onclick=()=>{closeDialog("ocrDialog");openHandwriting()};$("confirmOcrBtn").onclick=confirmOcr;$$('.feel-btn').forEach(b=>b.onclick=()=>{state.selectedFeel=b.dataset.feel;$$('.feel-btn').forEach(x=>x.classList.toggle('on',x===b))});$("saveProfileBtn").onclick=saveProfile;$("saveCompleteBtn").onclick=saveComplete;$("timelineSearchBtn").onclick=()=>{openDialog("searchDialog");setTimeout(()=>$("globalSearchInput").focus(),50)};$("globalSearchInput").addEventListener("input",renderSearch);$("timelineExportBtn").onclick=()=>openExport();$("printBtn").onclick=doPrint;$("jsonBackupBtn").onclick=backupJson;$("jsonRestoreInput").addEventListener("change",e=>{const f=e.target.files?.[0];if(f)restoreJson(f);e.target.value=""});window.addEventListener("online",()=>{toast("인터넷에 연결되었습니다. 동기화를 확인합니다.");flushSync()});window.addEventListener("offline",()=>{toast("오프라인입니다. 기록은 기기에 안전하게 저장됩니다.");updateSyncInfo()});
}
function renderBookPicker(){const books=readingBooks();$("bookPickerList").innerHTML=books.length?books.map(s=>{const p=getProfile(s.id);return `<div class="picker-row">${s.image?`<img src="${esc(s.image)}" alt="">`:`<div style="width:48px;height:68px;background:var(--panel2);border-radius:7px"></div>`}<div><h3>${esc(s.title)}</h3><p>${esc(s.creator||"")} · ${esc(serviceText(p))}${p.currentLocator?` · ${esc(p.currentLocator)}`:""}</p></div><button class="btn soft" data-pick-book="${esc(s.id)}" type="button">선택</button></div>`}).join(""):`<div class="empty-card">읽는 중인 책이 없습니다.</div>`}
async function boot(){state.idb=await openIdb();await loadSnapshot();bindEvents();setupHandwriting();renderAll();updateSyncInfo();initFirebase().catch(err=>{console.error(err);$("authGate").classList.remove("hidden");$("authGateStatus").textContent=`Firebase 연결 실패: ${err.message}`})}
boot();
